// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry 一份备份归档的描述。
 */
export interface Entry {
    /**
     * 文件名（不含路径）
     */
    "file": string;

    /**
     * 绝对路径
     */
    "path": string;
    "size": number;
    "at": string;
}
