// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveEntry 归档内一个条目（路径为 tar 头原样，如 home/kentrl/phpbox/.env）。
 */
export interface ArchiveEntry {
    "path": string;

    /**
     * tar 头声明的字节（目录为 0）
     */
    "size": number;
    "isDir": boolean;
}

/**
 * ArchiveInfo 归档内容摘要（流式读取，上限截断如实标注）。
 */
export interface ArchiveInfo {
    "entries": ArchiveEntry[] | null;

    /**
     * 达到 maxEntries 上限，未读完（如实标注，不冒充全量）
     */
    "truncated": boolean;

    /**
     * 已读条目的声明字节和（截断时是部分和）
     */
    "totalBytes": number;
}

/**
 * Entry 一份备份归档的描述。
 */
export interface Entry {
    /**
     * 文件名（不含路径）
     */
    "file": string;

    /**
     * 绝对路径
     */
    "path": string;
    "size": number;
    "at": string;
}
