// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry 一个站点的描述。
 */
export interface Entry {
    "domain": string;

    /**
     * vhost upstream 指向的 PHP 服务键（如 php84）
     */
    "php": string;

    /**
     * 站点目录（/var/www/<域名> 容器路径映射 WWW_ROOT/<域名>）
     */
    "root": string;

    /**
     * 域名是否已在 /etc/hosts 解析（127.0.0.1）
     */
    "hosts": boolean;
}
