// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backup 暴露备份归档管理能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../engine/backup/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteBackup 删除一份归档文件（GUI 侧已做三条件危险确认；此处拒绝含路径的文件名，防目录逃逸）。
 */
export function DeleteBackup(name: string): $CancellablePromise<void> {
    return $Call.ByID(2539003230, name);
}

/**
 * ExportBackup 弹原生保存对话框把归档复制到任意目录（backups/ 本体不动）。
 * 返回目标路径；取消返回空串（用户主动取消不是失败）。
 */
export function ExportBackup(name: string): $CancellablePromise<string> {
    return $Call.ByID(25094427, name);
}

/**
 * InspectBackup 查看归档内容（gzip/tar 头流式解析，不解压文件）。
 * 与 DeleteBackup 同款文件名校验（防目录逃逸）。
 */
export function InspectBackup(name: string): $CancellablePromise<backup$0.ArchiveInfo> {
    return $Call.ByID(88395047, name);
}

/**
 * ListBackups 列出全部备份归档（新在前）。
 */
export function ListBackups(): $CancellablePromise<$models.BackupEntry[] | null> {
    return $Call.ByID(1630183006);
}
