// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backup 暴露备份归档管理能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteBackup 删除一份归档文件（GUI 侧已做三条件危险确认；此处拒绝含路径的文件名，防目录逃逸）。
 */
export function DeleteBackup(name: string): $CancellablePromise<void> {
    return $Call.ByID(2539003230, name);
}

/**
 * ListBackups 列出全部备份归档（新在前）。
 */
export function ListBackups(): $CancellablePromise<$models.BackupEntry[] | null> {
    return $Call.ByID(1630183006);
}
