// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Creds 暴露服务连接凭证读取能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetServicePassword 返回某版本密码明文（连接抽屉点击显示时调用）。
 * 版本必须真实已安装（labels 校验），不存在返回空串（不报错——UI 显示"无密码"）。
 */
export function GetServicePassword(svc: string, ver: string): $CancellablePromise<string> {
    return $Call.ByID(2468335038, svc, ver);
}

/**
 * ListCreds 返回某服务全部已装版本的连接信息（端口/用户/掩码 DSN；密码只报存在）。
 * versions 由前端 installed（容器 labels 事实源）传入，绑定不重复派生。
 */
export function ListCreds(svc: string, versions: string[] | null): $CancellablePromise<$models.Cred[] | null> {
    return $Call.ByID(1069420609, svc, versions);
}
