// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Diag 暴露诊断包导出能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ExportDiagnosticBundle 弹原生保存对话框选目标路径，写入诊断包文本。
 * 返回实际写入路径；取消返回空串（用户主动取消不是失败，无错误）。
 */
export function ExportDiagnosticBundle(): $CancellablePromise<string> {
    return $Call.ByID(1603162897);
}
