// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Docker 暴露容器管理能力；导出方法会被 wails3 生成前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DetectFaults 扫描异常容器日志做已知故障模式匹配（只读；一键修复属 v1.1 引擎期，不提供）。
 */
export function DetectFaults(): $CancellablePromise<$models.FaultHit[] | null> {
    return $Call.ByID(1519738739);
}

/**
 * FaultModes 返回全部已知故障模式定义（诊断页参考表；CLI 兜底均为 bash 实测签名）。
 */
export function FaultModes(): $CancellablePromise<$models.FaultMode[] | null> {
    return $Call.ByID(999781109);
}

/**
 * GetContainerLogs 读容器最后 tail 行日志（诊断视图；tail 0/越界回退 50）。
 */
export function GetContainerLogs(name: string, tail: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(4191494093, name, tail);
}

/**
 * ListContainers 返回全部容器（含已停止）。
 */
export function ListContainers(): $CancellablePromise<$models.ContainerSummary[] | null> {
    return $Call.ByID(3894456769);
}
