// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Docker 暴露容器管理能力；导出方法会被 wails3 生成前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListContainers 返回全部容器（含已停止）。
 */
export function ListContainers(): $CancellablePromise<$models.ContainerSummary[] | null> {
    return $Call.ByID(3894456769);
}
