// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Env 暴露 .env 读写能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PatchEnv 更新白名单内的键。白名单外的键直接拒绝（而非忽略），让调用方明确失败。
 */
export function PatchEnv(changes: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(1990354771, changes);
}

/**
 * ReadEnv 返回全部 .env 条目（含可编辑标记）。
 */
export function ReadEnv(): $CancellablePromise<$models.EnvKV[] | null> {
    return $Call.ByID(2871044905);
}
