// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GoProjects 暴露 Go 项目发现能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListGoImages 列出本机 golang:* 镜像及被引用状态（uninstall 前置事实）。
 * 装卸本身经 Runner spawn `phpbox go install/uninstall`（事务在 bash 侧）。
 */
export function ListGoImages(): $CancellablePromise<$models.GoImage[] | null> {
    return $Call.ByID(2055806085);
}

/**
 * ListGoProjects 列出自动发现的 Go 项目及运行状态。
 */
export function ListGoProjects(): $CancellablePromise<$models.GoProjectEntry[] | null> {
    return $Call.ByID(2010355789);
}
