// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GoProjects 暴露 Go 项目发现能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListGoProjects 列出自动发现的 Go 项目及运行状态。
 */
export function ListGoProjects(): $CancellablePromise<$models.GoProjectEntry[] | null> {
    return $Call.ByID(2010355789);
}
