// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../engine/backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as docker$0 from "../engine/docker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goproject$0 from "../engine/goproject/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as offline$0 from "../engine/offline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as site$0 from "../engine/site/models.js";

/**
 * BackupEntry 透传引擎类型。
 */
export type BackupEntry = backup$0.Entry;

/**
 * ContainerSummary 透传引擎类型（前端 TS 类型由绑定生成器产出）。
 */
export type ContainerSummary = docker$0.ContainerSummary;

/**
 * GoProjectEntry 透传引擎类型。
 */
export type GoProjectEntry = goproject$0.Entry;

/**
 * OfflineEntry 透传引擎类型。
 */
export type OfflineEntry = offline$0.Entry;

/**
 * OfflineResult 透传引擎类型。
 */
export type OfflineResult = offline$0.Result;

/**
 * SiteEntry 透传引擎类型。
 */
export type SiteEntry = site$0.Entry;
