// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../engine/backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as creds$0 from "../engine/creds/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as docker$0 from "../engine/docker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as faultmode$0 from "../engine/faultmode/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goimages$0 from "../engine/goimages/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goproject$0 from "../engine/goproject/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as health$0 from "../engine/health/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as offline$0 from "../engine/offline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as presence$0 from "../engine/presence/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as site$0 from "../engine/site/models.js";

/**
 * BackupEntry 透传引擎类型。
 */
export type BackupEntry = backup$0.Entry;

/**
 * ContainerMem 透传引擎类型（§3.5 版本卡内存占用）。
 */
export type ContainerMem = docker$0.ContainerMem;

/**
 * ContainerSummary 透传引擎类型（前端 TS 类型由绑定生成器产出）。
 */
export type ContainerSummary = docker$0.ContainerSummary;

/**
 * Cred 透传引擎类型。
 */
export type Cred = creds$0.Cred;

/**
 * DirUsage 一个目录的占用（路径 + 真实字节；目录不存在为 0）。
 */
export interface DirUsage {
    "label": string;
    "path": string;
    "bytes": number;
}

/**
 * EnvKV 一个 .env 条目（Editable=是否允许 GUI 修改）。
 */
export interface EnvKV {
    "key": string;
    "value": string;
    "editable": boolean;
}

/**
 * FaultHit / FaultMode 透传引擎类型（§8.1 已知故障模式库，阶段 0 只读检测）。
 */
export type FaultHit = faultmode$0.Hit;

export type FaultMode = faultmode$0.Mode;

/**
 * GoImage 透传引擎类型（§3.7 镜像管理）。
 */
export type GoImage = goimages$0.GoImage;

/**
 * GoProjectEntry 透传引擎类型。
 */
export type GoProjectEntry = goproject$0.Entry;

/**
 * OfflineEntry 透传引擎类型。
 */
export type OfflineEntry = offline$0.Entry;

/**
 * OfflineResult 透传引擎类型。
 */
export type OfflineResult = offline$0.Result;

/**
 * PresenceStatus 透传引擎类型。
 */
export type PresenceStatus = presence$0.Status;

/**
 * ResourceUsage 总览资源小部件数据：镜像（Docker API）+ 各数据目录（.env 契约路径）。
 */
export interface ResourceUsage {
    "images": docker$0.ImageUsage;
    "dirs": DirUsage[] | null;

    /**
     * 单目录测量失败不影响整体（快照尽力而为）
     */
    "dirsErrs": string[] | null;
}

/**
 * SiteEntry 透传引擎类型。
 */
export type SiteEntry = site$0.Entry;

/**
 * SiteHealth 透传引擎类型（status: up/degraded/down + code + err）。
 */
export type SiteHealth = health$0.Result;
