// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Offline 暴露离线缓存管理能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListOfflineCache 列出全部离线缓存条目。
 */
export function ListOfflineCache(): $CancellablePromise<$models.OfflineEntry[] | null> {
    return $Call.ByID(86210433);
}

/**
 * PruneOfflineCache 清理一条缓存目录（GUI 已做三条件危险确认；引擎侧再做服务白名单+版本防逃逸）。
 */
export function PruneOfflineCache(svc: string, ver: string): $CancellablePromise<void> {
    return $Call.ByID(3122538017, svc, ver);
}

/**
 * VerifyOfflineCache 校验一条缓存（镜像 tar gzip+tar 头 / PHP apk+pecl 闭包）。
 */
export function VerifyOfflineCache(svc: string, ver: string): $CancellablePromise<$models.OfflineResult> {
    return $Call.ByID(1546894048, svc, ver);
}
