// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Presence 暴露引擎存在性检测能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Detect 返回三条件快照（引擎目录 / CLI PATH / Docker 可达）。
 */
export function Detect(): $CancellablePromise<$models.PresenceStatus> {
    return $Call.ByID(791333481);
}
