// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Runner spawn phpbox CLI 并流式转发输出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * RunTask spawn bash phpbox CLI 并流式返回输出（事件名 task:log / task:done）。
 */
export function RunTask(args: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3889977853, args);
}
