// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Shell 暴露宿主桌面集成能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenInFileManager 用系统文件管理器打开目录（站点根目录等）。
 * 目录不存在时原样返回错误，由前端如实提示。
 */
export function OpenInFileManager(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2888815275, dir);
}

/**
 * OpenSiteBrowser 用系统默认浏览器打开站点 URL。
 * url 必须是 http(s) 完整地址（前端拼接端口）；WebView 内 <a target=_blank> 不可靠，统一走此绑定。
 */
export function OpenSiteBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(421314606, url);
}
