// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stats 暴露资源占用统计能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetResourceUsage 汇总镜像与数据目录占用。数据目录路径取 .env 契约键
 * （env.sh:64/80/81 默认值对齐）：WWW_ROOT/MYSQL_DATA_ROOT/PGSQL_DATA_ROOT + 离线库。
 */
export function GetResourceUsage(): $CancellablePromise<$models.ResourceUsage> {
    return $Call.ByID(3079122597);
}
