// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Terminal 暴露嵌入式终端能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * TerminalResize xterm cols/rows 变化同步 PTY 窗口尺寸。
 */
export function TerminalResize(cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3637055909, cols, rows);
}

/**
 * TerminalRunning 是否有活动会话（前端切路由时恢复 UI 状态用）。
 */
export function TerminalRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1195680480);
}

/**
 * TerminalStart 启动终端会话（$SHELL 固定为 bash/sh + TERM=xterm-256color）。
 * 已有会话时返回错误（前端应先 StopTerminal——同 daemon 单槽语义）。
 */
export function TerminalStart(dir: string): $CancellablePromise<void> {
    return $Call.ByID(3806870667, dir);
}

/**
 * TerminalStop 关闭会话（master 关闭 → shell 收 SIGHUP 退出，输出泵自然结束清槽）。
 */
export function TerminalStop(): $CancellablePromise<void> {
    return $Call.ByID(2822954873);
}

/**
 * TerminalWrite 用户键入原样写入 PTY（回显由行规程做，绑定不加工）。
 */
export function TerminalWrite(data: string): $CancellablePromise<void> {
    return $Call.ByID(2024858960, data);
}
