// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry 一条离线缓存记录（一个服务版本目录）。
 */
export interface Entry {
    /**
     * php / mysql / pgsql / redis / nginx
     */
    "svc": string;

    /**
     * 裸版本号；nginx 用镜像 tag（如 alpine）
     */
    "ver": string;

    /**
     * 绝对路径
     */
    "path": string;

    /**
     * 目录递归总字节数
     */
    "size": number;
    "files": number;

    /**
     * image-tar（单 tar）/ closure（apk+pecl 闭包）
     */
    "kind": string;
}

/**
 * Result 校验结论。
 */
export interface Result {
    "ok": boolean;
    "detail": string;
}
