// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GoImage 一条 Go 镜像状态（全部由 Docker 真实状态派生）。
 */
export interface GoImage {
    /**
     * CLI 参数形态：alpine / 1.24 / 1.24.3（用户装卸用它）
     */
    "tag": string;

    /**
     * 完整镜像名：golang:alpine / golang:1.24-alpine
     */
    "image": string;

    /**
     * 字节
     */
    "size": number;

    /**
     * 被容器使用（docker ancestor 语义）——bash uninstall 会拒绝
     */
    "inUse": boolean;

    /**
     * 引用它的容器名（可能多个，逗号连接；未用为空）
     */
    "usedBy": string;

    /**
     * .env GO_DEFAULT_VERSION 指向的版本（当前默认）
     */
    "default": boolean;
}
