// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Hit 一次检测结果：模式 + 命中的容器与命中行（证据，不是猜测）。
 */
export interface Hit {
    "mode": Mode;

    /**
     * 容器名
     */
    "container": string;

    /**
     * 命中的日志行（截断到最多 3 行）
     */
    "lines": string[] | null;
}

/**
 * Mode 一个已知故障模式的检测定义。
 */
export interface Mode {
    /**
     * 稳定标识（前端徽章/跳转用）
     */
    "id": string;

    /**
     * 模式名（中英由前端 i18n 按标题键处理——传固定 zh 键）
     */
    "title": string;

    /**
     * 日志关键词（任一命中即匹配；全部小写，匹配时统一 lower）
     */
    "match": string[] | null;

    /**
     * 受影响服务线（提示用，如 mysql/pgsql/nginx/php）
     */
    "scopes": string[] | null;

    /**
     * 真实 CLI 兜底命令（grep 核实存在的子命令组合）
     */
    "cli": string;
}
