// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status 引擎就绪度快照（三条件独立呈现，不合并成单一布尔——开发者要分别知道缺什么）。
 */
export interface Status {
    /**
     * ~/phpbox 目录存在（install.sh 的固定布局）
     */
    "EngineDir": boolean;

    /**
     * exec.LookPath("phpbox") 结果：可执行文件绝对路径；空 = 不在 PATH
     */
    "CliInPath": string;

    /**
     * ~/phpbox/.env 存在（引擎已初始化过的标志）
     */
    "HasEnv": boolean;

    /**
     * Docker Engine 可达（1s ping）
     */
    "DockerOK": boolean;

    /**
     * Docker 不可达原因（可呈现给开发者）
     */
    "DockerErr": string;
}
