// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ContainerSummary 是容器列表的引擎输出（phpbox 管理视角，非 docker 原生结构）。
 */
export interface ContainerSummary {
    /**
     * 容器名（去前导斜杠）
     */
    "Name": string;
    "Image": string;

    /**
     * running / exited / paused ...
     */
    "State": string;

    /**
     * phpbox-service label（如 php/mysql；非 phpbox 容器为空）
     */
    "Service": string;

    /**
     * phpbox-version label（如 8.4；php 线含点，与 compose 分片名一致）
     */
    "Version": string;
}

/**
 * ImageStat 一条镜像的占用摘要（phpbox 管理视角过滤可选）。
 */
export interface ImageStat {
    /**
     * 短 ID（12 位）
     */
    "ID": string;

    /**
     * 仓库标签（顶层多个 repo:tag）
     */
    "Tags": string[] | null;

    /**
     * 字节（docker image ls SIZE）
     */
    "Size": number;

    /**
     * 是否被任何容器使用（docker system df ACTIVE 语义）
     */
    "InUse": boolean;
}

/**
 * ImageUsage 镜像占用汇总：总量 + 明细（按大小降序）。
 */
export interface ImageUsage {
    /**
     * 全部镜像字节和
     */
    "Total": number;

    /**
     * 正被容器使用的镜像字节和
     */
    "Used": number;
    "Items": ImageStat[] | null;
}
