// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ContainerSummary 是容器列表的引擎输出（phpbox 管理视角，非 docker 原生结构）。
 */
export interface ContainerSummary {
    /**
     * 容器名（去前导斜杠）
     */
    "Name": string;
    "Image": string;

    /**
     * running / exited / paused ...
     */
    "State": string;
}
