// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Result 探测结果（结构化返回，前端映射徽章）。
 */
export interface Result {
    "status": Status;

    /**
     * HTTP 状态码（Down 时 0）
     */
    "code": number;

    /**
     * 连接失败原因（Down 时非空）
     */
    "err"?: string;
}

/**
 * Status 站点健康三态（UI 规格 §3.1：🟢 正常 / 🟡 降级 / ⚪ 未启动）。
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 2xx/3xx：nginx 服务中
     */
    Up = "up",

    /**
     * 4xx/5xx：有响应但异常（404 无索引 / 502 PHP 容器异常）
     */
    Degraded = "degraded",

    /**
     * 连接失败：nginx 未启动或端口未监听
     */
    Down = "down",
};
