// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry 一个 Go 项目。
 */
export interface Entry {
    /**
     * 项目名（目录名，即 CLI 参数形态）
     */
    "name": string;

    /**
     * 绝对路径
     */
    "dir": string;
    "running": boolean;
}
