// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cred 一个服务版本的连接信息（全部真实值；密码仅在显式请求时填入）。
 */
export interface Cred {
    /**
     * php / mysql / pgsql / redis
     */
    "service": string;

    /**
     * 8.0（含点，与 label 一致）
     */
    "version": string;

    /**
     * .env PORT 键；缺失为空（用 bash 默认由调用方决定）
     */
    "port": string;

    /**
     * bash 契约：mysql/pgsql root/postgres；redis 空（密码认证）
     */
    "user": string;

    /**
     * 密码键存在（不返回值——请求时单独取）
     */
    "hasPass": boolean;

    /**
     * 掩码 DSN（密码段 ***）——展示用
     */
    "dsnMask": string;
}
